version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      backstage:
        patterns: ["@backstage/*"]
      dev:
        dependency-type: "development"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"
